---

detectors:
  IrresponsibleModule:
    enabled: false

  ControlParameter:
    exclude:
      - OnStrum::Logs::Configuration#raise_unless
      - OnStrum::Logs::Configuration#valid_argument_type?

  UtilityFunction:
    exclude:
      - OnStrum::Logs::Configuration#valid_argument_type?
      - OnStrum::Logs::Logger::Default#configuration
      - OnStrum::Logs::Configuration#instance_initializer

  FeatureEnvy:
    exclude:
      - OnStrum::Logs::Logger::Default#hash_normalizer

  Attribute:
    exclude:
      - OnStrum::Logs::Configuration#detailed_formatter

  TooManyStatements:
    exclude:
      - OnStrum::Logs::Logger::Default#hash_normalizer

exclude_paths:
  - spec/support/helpers
